version: "3.7"

services:
  keycloak:
    image: jboss/keycloak
    depends_on:
      - keycloak-postgres
    volumes:
      - ./keycloak/realm-config:/opt/jboss/keycloak/realm-config
    command:
      [
          '-b',
          '0.0.0.0',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-postgres:5432
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8080:8080

  keycloak-postgres:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
    - 5432:5432

  todo-service:
    build: ./todo-service
    depends_on:
      - todo-service-postgres
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-service-postgres:5432/todo_service
      - SPRING_DATASOURCE_USERNAME=todo_service
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/auth/realms/todo-app
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak:8080/auth/realms/todo-app/protocol/openid-connect/certs
    ports:
      - 8081:8081

  todo-service-postgres:
    image: "postgres:12-alpine"
    restart: always
    environment:
      - POSTGRES_DB=todo_service
      - POSTGRES_USER=todo_service
      - POSTGRES_PASSWORD=password
    ports:
    - 5433:5432

  todo-client:
    build: ./todo-client
    depends_on:
      - todo-service
      - keycloak
    restart: always
    environment:
      - APP_SERVICES_TODO_SERVICE_URI=http://todo-service:8081/todo
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI=http://keycloak:8080/auth/realms/todo-app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TODO-CLIENT_CLIENT-SECRET=1f5124d0-9ab6-4477-a695-499129468440
    ports:
      - 8082:8082

  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - keycloak
    environment:
      - SLEEP_LENGTH=3
    command: keycloak:8080