version: "3.7"

services:
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_IMPORT=/tmp/todo-app-realm.json
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db:5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8180:8080
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak/todo-app-realm.json:/tmp/todo-app-realm.json

  keycloak-db:
    image: "postgres:12-alpine"
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - keycloak-db:/var/lib/postgres/data

  todo-service-db:
    image: "postgres:12-alpine"
    restart: always
    environment:
      - POSTGRES_DB=todo_service
      - POSTGRES_USER=todo_service
      - POSTGRES_PASSWORD=password
    volumes:
      - todo-service-db:/var/lib/postgres/data
    ports:
      - 5432:5432

volumes:
  keycloak-db: {}
  todo-service-db: {}