server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/todo_service
    username: todo_service
    password: password
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/todo-app
          jwk-set-uri: http://localhost:8080/auth/realms/todo-app/protocol/openid-connect/certs

logging.level:
  root: INFO
  org.springframework.security: DEBUG
  org.springframework.web: DEBUG
  com.mikhailkarpov: DEBUG