server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_service
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/auth/realms/todo-app/protocol/openid-connect/certs