server.port: 8080

spring:
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          todo-client:
            provider: keycloak
            client-id: todo-client
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/todo-app
            user-name-attribute: preferred_username

app:
  services:
    todo-service:
      uri: http://localhost:8081/todo

logging.level:
  root: INFO
  org.springframework.security: DEBUG
  com.mikhailkarpov: DEBUG
