server.port: 8080

spring:
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          todo-client:
            provider: keycloak
            client-id: todo-client
            client-secret: 1f5124d0-9ab6-4477-a695-499129468440
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/auth/realms/todo-app/openid-connect/auth
            token-uri: http://localhost:8180/auth/realms/todo-app/openid-connect/token
            user-info-uri: http://localhost:8180/auth/realms/todo-app/openid-connect/userinfo
            jwk-set-uri: http://localhost:8180/auth/realms/todo-app/openid-connect/certs
            user-name-attribute: preferred_username

app:
  services:
    todo-service:
      uri: http://localhost:8081/todo

logging.level:
  root: INFO
  org.springframework.security: DEBUG
  com.mikhailkarpov: DEBUG
